[package]
name = "screamreader-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ringbuf = "0.2.8"
cpal = "0.14.0"
byteorder = "1.4.3"